"""
app.py
------
Streamlit web app for the Loan Approval Predictor.

Run locally:
    streamlit run app.py

This is the file Streamlit Community Cloud runs when you deploy the repo.
"""

from pathlib import Path
import sys

import streamlit as st

sys.path.append(str(Path(__file__).resolve().parent / "src"))
from predict import LoanApprovalModel  # noqa: E402

st.set_page_config(page_title="Loan Approval Predictor", page_icon="🏦", layout="centered")


@st.cache_resource
def get_model() -> LoanApprovalModel:
    return LoanApprovalModel()


st.title("🏦 Loan Approval Predictor")
st.write(
    "Fill in the applicant's details below and get an instant, "
    "model-based prediction of whether the loan is likely to be approved."
)

try:
    model = get_model()
except FileNotFoundError as e:
    st.error(str(e))
    st.stop()

with st.form("loan_form"):
    st.subheader("Applicant Details")
    col1, col2 = st.columns(2)

    with col1:
        applicant_income = st.number_input("Applicant Income (monthly)", min_value=0, value=50000, step=1000)
        coapplicant_income = st.number_input("Coapplicant Income (monthly)", min_value=0, value=0, step=1000)
        age = st.number_input("Age", min_value=18, max_value=100, value=30)
        dependents = st.number_input("Number of Dependents", min_value=0, max_value=10, value=0)
        credit_score = st.number_input("Credit Score", min_value=300, max_value=900, value=700)
        existing_loans = st.number_input("Existing Loans", min_value=0, max_value=10, value=0)
        dti_ratio = st.slider("Debt-to-Income Ratio", 0.0, 1.0, 0.3, step=0.01)
        savings = st.number_input("Savings", min_value=0, value=20000, step=1000)

    with col2:
        collateral_value = st.number_input("Collateral Value", min_value=0, value=100000, step=1000)
        loan_amount = st.number_input("Loan Amount Requested", min_value=0, value=200000, step=1000)
        loan_term = st.number_input("Loan Term (months)", min_value=1, max_value=480, value=180)
        employment_status = st.selectbox(
            "Employment Status", ["Salaried", "Self-employed", "Contract", "Unemployed"]
        )
        marital_status = st.selectbox("Marital Status", ["Married", "Single"])
        loan_purpose = st.selectbox(
            "Loan Purpose", ["Personal", "Car", "Business", "Home", "Education"]
        )
        property_area = st.selectbox("Property Area", ["Urban", "Semiurban", "Rural"])
        education_level = st.selectbox("Education Level", ["Graduate", "Not Graduate"])
        gender = st.selectbox("Gender", ["Male", "Female"])
        employer_category = st.selectbox(
            "Employer Category", ["Private", "Government", "MNC", "Business", "Unemployed"]
        )

    submitted = st.form_submit_button("Predict Loan Approval")

if submitted:
    applicant = {
        "Applicant_Income": applicant_income,
        "Coapplicant_Income": coapplicant_income,
        "Employment_Status": employment_status,
        "Age": age,
        "Marital_Status": marital_status,
        "Dependents": dependents,
        "Credit_Score": credit_score,
        "Existing_Loans": existing_loans,
        "DTI_Ratio": dti_ratio,
        "Savings": savings,
        "Collateral_Value": collateral_value,
        "Loan_Amount": loan_amount,
        "Loan_Term": loan_term,
        "Loan_Purpose": loan_purpose,
        "Property_Area": property_area,
        "Education_Level": education_level,
        "Gender": gender,
        "Employer_Category": employer_category,
    }

    result = model.predict(applicant)

    st.divider()
    if result["approved"]:
        st.success(f"✅ Loan likely to be **APPROVED** ({result['approval_probability']:.1%} confidence)")
    else:
        st.error(f"❌ Loan likely to be **REJECTED** ({(1 - result['approval_probability']):.1%} confidence)")

    st.progress(result["approval_probability"])
    st.caption(
        "This prediction is generated by a machine learning model trained on historical "
        "data. It is a demo project and should not be used for real lending decisions."
    )

st.divider()
st.caption(f"Model in use: `{model.model_name}` — trained with scikit-learn.")
